# -*- coding: utf-8 -*-
print ("Hello world!")
print ("Hello again")
print ("I like to type this.")
print ("This is fun.")
print ("Yay! Pring.")
print ("I'd much rather you 'not'")
print ('I "said" do not touch this.')
print ("打中文試試看")
print ("可以直接打中文")